#!/bin/bash
# If possible, create the /dev/kvm device node.
#
set -e
#
cd base ; docker build -t srbala/openqa:base-al9 -f Dockerfile .
cd ../webui ; docker build -t srbala/openqa:webui-al9 -f Dockerfile .
cd ../worker ; docker build -t srbala/openqa:worker-al9 -f Dockerfile .
cd ..
