#!/bin/bash
# If possible, create the /dev/kvm device node.
#
set -e
#
cd base ; docker buildx build --platform=linux/amd64,linux/arm64,linux/ppc64le,linux/s390x -t almalinux/openqa:base-al9 --push -f Dockerfile .
cd ../webui ; docker buildx build --platform=linux/amd64,linux/arm64,linux/ppc64le,linux/s390x -t almalinux/openqa:webui-al9 --push -f Dockerfile .
cd ../worker ; docker buildx build --platform=linux/amd64,linux/arm64,linux/ppc64le,linux/s390x -t almalinux/openqa:worker-al9 --push -f Dockerfile .
cd ..
