#!/bin/bash
# If possible, create the /dev/kvm device node.
#
set -e
#
cd base ; docker build -t almalinux/openqa:base-fedora -f Dockerfile.fedora .
cd ../webui ; docker build -t almalinux/openqa:webui-fedora -f Dockerfile.fedora .
cd ../worker ; docker build -t almalinux/openqa:worker-fedora -f Dockerfile.fedora .
cd ..
